export const defaultWidgets = [
  {
    widget_name: "Analog Clocks",
    widget_description: "Analog Clocks",
    visible: true,
    x: 0,
    y: 0,
    w: 3,
    h: 1,
    i: "0",
  },
  {
    widget_name: "Embed Widget",
    widget_description: "Embed Widget",
    visible: true,
    x: 3,
    y: 0,
    w: 3,
    h: 1,
    i: "1",
  },
  {
    widget_name: "Quotes",
    widget_description: "Quotes",
    visible: true,
    x: 6,
    y: 0,
    w: 3,
    h: 1,
    i: "2",
  },
  {
    widget_name: "RSS News Reader",
    widget_description: "RSS News Reader",
    visible: true,
    x: 9,
    y: 0,
    w: 3,
    h: 1,
    i: "3",
  },
  {
    widget_name: "Crypto StockChart",
    widget_description: "Crypto StockChart",
    visible: true,
    x: 0,
    y: 1,
    w: 3,
    h: 1,
    i: "4",
  },
  {
    widget_name: "Crypto Portfolio Tracker",
    widget_description: "Crypto Portfolio Tracker",
    visible: true,
    x: 3,
    y: 1,
    w: 3,
    h: 1,
    i: "5",
  },
  {
    widget_name: "Crypto Price Ticker",
    widget_description: "Crypto Price Ticker",
    visible: true,
    x: 6,
    y: 1,
    w: 3,
    h: 1,
    i: "6",
  },
];

export const defaultLayout = [
  {
    layout_id: 1,
    layout_name: "Default",
  },
];

export const defaultAssociation = [
  { layout_id: 1, widget_id: 1 },
  { layout_id: 1, widget_id: 2 },
  { layout_id: 1, widget_id: 3 },
  { layout_id: 1, widget_id: 4 },
  { layout_id: 1, widget_id: 5 },
  { layout_id: 1, widget_id: 6 },
  { layout_id: 1, widget_id: 7 },
];
